<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>true</ImplicitUsings>
    <IncludeSymbols>true</IncludeSymbols>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Backend.Fx.Execution.Abstractions" Version="1.1.11" />
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference
      Include="Microsoft.SourceLink.GitHub"
      Version="10.0.401"
      PrivateAssets="All"
    />
  </ItemGroup>
</Project>
